### ISSUE TITLE
Some problems while using mMFJ

### ISSUE THREAD

**Issue by Wen-Hao-Wu** [GonghengZhang/mMFJ#1]
Hi, I'm interesting in this extension for computing enhanced F-J method. However, there are some problem while compliing the CC-FJpy after replacing the "src" files.
First, the functions that you developed (such as FY0_Y2, FJ0_J2, FY0Y2... etc.) are not include in the "FJgpu.hh". This will cause error while compling the package.
Second, after I add the functions in "FJgpu.hh", it can be successfully compiled. However, while I using the "fj_noise_v2" function as the instructions in mMFJ.py. I met the ImportError with undefined symbol: FJ0J2. I guess it is because the "FJgpu.cu" does not include the new functions.
Could you show the complete steps while modifying the CC-FJpy package? or there is something I was doing wrong?

Thank you.

**Comment by GonghengZhang** [comment]
I have updated the code files, you can try again.
